### PR TITLE
{{fi-url}} for more dynamic use of the jFiler solution.

### PR DESCRIPTION
**Pull request by s0By**
In the project we used jFiler not only to upload files in a great and simple way. 
But also to show preloaded files without the ability to upload. 

Example to achieve this:

```javascript
changeInput: '<div></div>' 
```

this way we eliminate the input

Thanks to our small change in filer code we now how an extra variable {{fi-url}} which we could use like this:
```javascript
itemAppend: '<li class="jFiler-item">\
                            <div class="jFiler-item-container">\
                                <div class="jFiler-item-inner">\
                                    <div class="jFiler-item-thumb">\
                                        {{fi-image}}\
                                    </div>\
                                    <div class="jFiler-item-info">\
                                        <span class="jFiler-item-title"><b title="{{fi-name}}">{{fi-name | limitTo: 25}}</b></span>\
                                        <span class="jFiler-item-size">{{fi-size2}}</span>\
                                        <div class="jFiler-item-assets">\
                                        <ul class="list-inline pull-left">\
                                            <li><span class="jFiler-item-others">{{fi-icon}}</span></li>\
                                        </ul>\
                                        </div>\
                                    </div>\
                                    <div class="jFiler-item-download">\
                                        <a class="fa fa-download" href="{{fi-url}}"></a>\
                                    </div>\
                                </div>\
                            </div>\
                        </li>'
```

### CODE REVIEW

**Comment by cpoissonnier** [comment]
That's exactly what I need, you should merge this PR !

**Comment by CreativeDream** [comment]
@s0By @cpoissonnier now [v1.2](https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.2)

**Comment by cpoissonnier** [comment]
Thanks for the amazing job, it is in time to be on the next version of my project !

**Comment by CreativeDream** [comment]
@cpoissonnier very glad :)

**Pull request closed without merging**
